<a href="https://colab.research.google.com/github/mateuszandzelak01/dc-bootcamp-udemy/blob/master/01_numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Podstawy

In [2]:
import numpy as np

In [3]:
np.__version__

'1.18.5'

**1D** **Array**

In [4]:
x = np.array([1,3])
x

array([1, 3])

In [5]:
type(x)

numpy.ndarray

In [6]:
x.ndim

1

In [7]:
x.shape

(2,)

In [8]:
x.size

2

In [9]:
x.dtype

dtype('int64')

**2D array**

In [10]:
x = np.array([[1,3,4],[5,9,6]])
print(x)

[[1 3 4]
 [5 9 6]]


In [11]:
x.shape

(2, 3)

**3D Array**

In [12]:
x = np.array([[[1,2,3],
              [2,3,4]],
              
             [[12, 34, 56],
              [3, 5, 7.8]]])

In [13]:
x.ndim

3

In [14]:
x.shape

(2, 2, 3)

**Typy danych**

In [15]:
A = np.array([True, False])
A.dtype

dtype('bool')

**Tworzenie tablic**

In [16]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.full(shape=(5,6), fill_value=5, dtype='int')

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(start=10, stop=20, step=0.6)

array([10. , 10.6, 11.2, 11.8, 12.4, 13. , 13.6, 14.2, 14.8, 15.4, 16. ,
       16.6, 17.2, 17.8, 18.4, 19. , 19.6])

In [21]:
np.linspace(start=10, stop=20, num=154)

array([10.        , 10.06535948, 10.13071895, 10.19607843, 10.26143791,
       10.32679739, 10.39215686, 10.45751634, 10.52287582, 10.58823529,
       10.65359477, 10.71895425, 10.78431373, 10.8496732 , 10.91503268,
       10.98039216, 11.04575163, 11.11111111, 11.17647059, 11.24183007,
       11.30718954, 11.37254902, 11.4379085 , 11.50326797, 11.56862745,
       11.63398693, 11.69934641, 11.76470588, 11.83006536, 11.89542484,
       11.96078431, 12.02614379, 12.09150327, 12.15686275, 12.22222222,
       12.2875817 , 12.35294118, 12.41830065, 12.48366013, 12.54901961,
       12.61437908, 12.67973856, 12.74509804, 12.81045752, 12.87581699,
       12.94117647, 13.00653595, 13.07189542, 13.1372549 , 13.20261438,
       13.26797386, 13.33333333, 13.39869281, 13.46405229, 13.52941176,
       13.59477124, 13.66013072, 13.7254902 , 13.79084967, 13.85620915,
       13.92156863, 13.9869281 , 14.05228758, 14.11764706, 14.18300654,
       14.24836601, 14.31372549, 14.37908497, 14.44444444, 14.50

In [22]:
x = np.arange(25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
x.reshape(5,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**Podstawowe działania**

In [24]:
A = np.array([2, 3, 5, 9])
B = np.array([0, -3, 15, 99])

In [25]:
A+B

array([  2,   0,  20, 108])

In [26]:
X = np.array([[2, 3], [115, 9]])
Y = np.array([[1, 99], [52, 9]])

In [27]:
X.dot(Y)

array([[  158,   225],
       [  583, 11466]])

**Generowanie liczb pseudolosowych**

In [32]:
X = np.random.seed(0)

In [34]:
print(X)

None


In [30]:
X = np.random.randn(10, 4)

In [31]:
X

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275]])

In [35]:
np.random.randint(low=10, high=200, size=15)

array([182,  57, 127,  77, 113,  19,  31,  46,  97,  80,  98, 150,  68,
        49,  97])

In [37]:
np.random.choice(['python', 'java', 'c++'])

'c++'

**Podstawowe funkcje**

In [38]:
A = np.random.rand(5)
A

array([0.56804456, 0.92559664, 0.07103606, 0.0871293 , 0.0202184 ])

In [39]:
np.argmax(A)

1

In [40]:
A[np.argmax(A)]

0.925596638292661

In [41]:
np.max(A)

0.925596638292661

In [42]:
np.min(A)

0.02021839744032572

In [43]:
np.mean(A)

0.33440499094526926

In [44]:
np.median(A)

0.08712929970154071

In [45]:
np.std(A)

0.3558979321062078

**Indeksowanie**

In [47]:
 A = np.arange(20)
 A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [61]:
A[1:4,1:5]

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [65]:
A[3,4] = 99
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 99]])

**Iteracja po tablicach**

In [66]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 99]])

In [84]:
for wiersz in A:
  print(wiersz[2:4])

[2 3]
[7 8]
[12 13]
[17 18]


In [85]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 99]])

In [86]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 99]])

In [88]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 99])

In [89]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 99]])

In [92]:
A > 4

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [97]:
A = A[A > 4]

In [100]:
A = A.reshape(3,5)

In [102]:
A

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 99]])

In [103]:
np.bitwise_and(A > 6, A < 14)

array([[False, False,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [False, False, False, False, False]])