<a href="https://colab.research.google.com/github/mateuszandzelak01/ds-bootcamp-udemy/blob/master/02_algebra_liniowaa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [2]:
import numpy as np

### <a name='a1'></a> Norma wektora, długość wektora w $R^{2}$

${\mathbf  {v}} = [v_{1}, v_{2}]$   
$\left\|{\mathbf  {v}}\right\|={\sqrt  {v_{1}^{2}+v_{2}^{2}}}$

In [ ]:
v1 = np.array([-2, 4])
v1

array([-2,  4])

In [ ]:
np.linalg.norm(v1)

4.47213595499958

### <a name='a2'></a> Norma euklidesowa w $R^{n}$

$\left\|{\mathbf  {v}}\right\|={\sqrt  {v_{1}^{2}+v_{2}^{2}+\cdots +v_{n}^{2}}}$

In [ ]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

### <a name='a3'></a> Odległóść dwóch punktów na płaszczyźnie


In [ ]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

### <a name='a4'></a> Odległóść dwóch punktów w przestrzeni $R^{n}$


 \begin{aligned}d(\mathbf {p} ,\mathbf {q} )=d(\mathbf {q} ,\mathbf {p} )&={\sqrt {(q_{1}-p_{1})^{2}+(q_{2}-p_{2})^{2}+\cdots +(q_{n}-p_{n})^{2}}}\\[8pt]&={\sqrt {\sum _{i=1}^{n}(q_{i}-p_{i})^{2}}}\end{aligned}



In [ ]:
p = np.array([3, 0, 10, 56, 78, 90])
q = np.array([0, 4, 55, 78, 88, 30])

np.linalg.norm(p - q)

78.95568377260753

### <a name='a5'></a> Mnożenie macierzy



$${A} ={\begin{bmatrix}a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\cdots &a_{mn}\\\end{bmatrix}}$$
A - macierz wymairu $m\ x\ n$

$$ {B} ={\begin{bmatrix}b_{11}&b_{12}&\cdots &b_{1p}\\b_{21}&b_{22}&\cdots &b_{2p}\\\vdots &\vdots &\ddots &\vdots \\b_{n1}&b_{n2}&\cdots &b_{np}\\\end{bmatrix}}$$
B - macierz wymairu $n\ x\ p$

$$C = AB$$ 
C - macierz wymiaru $m\ x\ p$  
Aby móc pomnożyć dwie macierze liczba liczba kolumn w lewej macierzy musi zgadzać się z liczbą wierszy prawej macierzy.

Mnożenie macierzy nie jest przemienne! Tzn. $$AB \neq BA$$




### Przykład 1
$ X = \begin{bmatrix}5&3\\3&9\end{bmatrix}$, $ Y= \begin{bmatrix}1\\-1\end{bmatrix} $  
$X$ macierz 2x2  
$Y$ macierz 2x1
$$Z = X \cdot Y = \begin{bmatrix}5&3\\3&9\end{bmatrix} \cdot \begin{bmatrix}1\\-1\end{bmatrix} = \begin{bmatrix}2\\-6\end{bmatrix}$$
$Z$ macierz 2x1


In [ ]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [ ]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [ ]:
Z.shape

(2, 1)

### Przykład 2
$X = \begin{bmatrix}2&-1&3\\3&1&0\end{bmatrix}$, $Y = \begin{bmatrix}2&1&-1\\0&-1&2\\3&2&0\end{bmatrix}$

$X$ macierz 2x3  
$Y$ macierz 3x3
$$Z = X \cdot Y =  \begin{bmatrix}2&-1&3\\3&1&0\end{bmatrix} \cdot \begin{bmatrix}2&1&-1\\0&-1&2\\3&2&0\end{bmatrix} = \begin{bmatrix}13&9&-4\\6&2&-1\end{bmatrix}$$
$Z$ macierz 2x3

In [ ]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [ ]:
np.dot(X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

### <a name='a6'></a> Wyznacznik macierzy

$${\displaystyle A={\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$$
$A$ - macierz wymiaru nxn

#### Oznaczenia:

${\displaystyle |A|=\left|{\begin{array}{c}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{array}}\right|} $  lub  $ {\displaystyle \det A=\det {\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$

#### Przykład:
${\displaystyle \det A={\begin{vmatrix}a_{11}&a_{12}\\a_{21}&a_{22}\end{vmatrix}}=a_{11}a_{22}-a_{12}a_{21}}$

${\displaystyle \det A={\begin{vmatrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\end{vmatrix}}=a_{11}a_{22}a_{33}+a_{21}a_{32}a_{13}+a_{31}a_{12}a_{23}-a_{21}a_{12}a_{33}-a_{11}a_{32}a_{23}-a_{31}a_{22}a_{13}}$

${\displaystyle \det A={\begin{vmatrix}2&4\\-1&3\end{vmatrix}}=2\cdot3-4\cdot(-1)} = 6 + 4 = 10 $


In [3]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10.0

### <a name='a7'></a> Ślad macierzy

$${\displaystyle A={\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$$
$A$ - macierz wymiaru nxn

${\displaystyle \operatorname {tr} (A)=\sum _{i=1}^{n}a_{ii}=a_{11}+a_{22}+\dots +a_{nn}}$

#### Przykład:
$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$

${\displaystyle \operatorname {tr} (A)=\sum _{i=1}^{2}a_{ii}=a_{11}+a_{22} = 2 + 3 = 5}$

In [4]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

###  <a name='a8'></a>  Macierz jednostkowa 

Macierz jednostkowa - macierz kwadratowa, której współczynniki podane są wzorem:
$${\displaystyle a_{ij}={\begin{cases}1\quad {\text{dla}}\quad i=j\\[2pt]0\quad {\text{dla}}\quad i\neq j\end{cases}}}$$

#### Przykłady
${\displaystyle I_{1}={\begin{bmatrix}1\end{bmatrix}},\;I_{2}={\begin{bmatrix}1&0\\0&1\end{bmatrix}},\;I_{3}={\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}}}$

In [5]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### <a name='a9'></a>  Macierz odwrotna

$A$ - macierz kwadratowa stopnia $n$. Macierz $A$ posiada macierz odwrotną, gdy istnieje macierz $B$, taka, że
$$AB = BA = I$$

$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$

In [7]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [8]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

### <a name='a10'></a> Macierz transponowana

Zamiana wierszy na kolumny i kolumny na wiersze.

#### Przykład 1:

$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$,
$A^{T} = \begin{bmatrix}2&-1\\4&3\end{bmatrix}$

#### Przykład 2:
$A = \begin{bmatrix}2&1&-1\\0&-1&2\end{bmatrix}$,
$A^{T} = \begin{bmatrix}2&0\\1&-1\\-1&2\end{bmatrix}$

In [9]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [10]:
A.T

array([[ 2, -1],
       [ 4,  3]])

### <a name='a11'></a> Rozwiązywanie układów równań
Rozważmy układ równań $U$:  
$${\displaystyle \mathrm {U} \colon {\begin{cases}{\begin{matrix}a_{11}x_{1}&+&a_{12}x_{2}&+&\dots &+&a_{1n}x_{n}&=b_{1},\\a_{21}x_{1}&+&a_{22}x_{2}&+&\dots &+&a_{2n}x_{n}&=b_{2},\\\vdots &&\vdots &&\ddots &&\vdots &\vdots \\a_{m1}x_{1}&+&a_{m2}x_{2}&+&\dots &+&a_{mn}x_{n}&=b_{m}.\end{matrix}}\end{cases}}.}$$

Wykorzystując macierze możemy to przedstawić następująco:

$${\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\dots &a_{mn}\end{bmatrix}}{\begin{bmatrix}x_{1}\\x_{2}\\\vdots \\x_{n}\end{bmatrix}}={\begin{bmatrix}b_{1}\\b_{2}\\\vdots \\b_{m}\end{bmatrix}}$$
I w zapisie skrótowym:
$$\mathbf {AX} =\mathbf {B}$$

Gdzie:  
$A = {\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\dots &a_{mn}\end{bmatrix}}$ - macierz współczynników

${\displaystyle \mathbf {B} =[b_{1},b_{2},\dots ,b_{m}]} $ - wektor wyrazów wolnych  
${\mathbf  X}=[x_{1},x_{2},\dots ,x_{n}] $ - wektor niewiadomych

Jeśli macierz układu $A$ jest macierzą kwadratową, to oznaczoność układu jest równoważna jej odwracalności, tzn.
$$\mathbf {AX} =\mathbf {B}$$
$${\displaystyle \mathbf {A} ^{-1}\mathbf {AX} =\mathbf {A} ^{-1}\mathbf {B}} $$
$$\mathbf {X} =\mathbf {A} ^{-1}\mathbf {B} .$$

#### Przykład:
Rozważmy układ równań:
$$\begin{cases}2x + 4y = 10 \\ x - y = -1 \end{cases}$$  
Rozwiązaniem jest para liczb:
$$\begin{cases}x = 1 \\ y = 2 \end{cases}$$  






In [11]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [12]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [13]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [14]:
X.shape

(2, 1)